//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATSMiniProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Application()
        {
            this.CandidateFiles = new HashSet<CandidateFile>();
            this.Interviews = new HashSet<Interview>();
            this.ApplicationStatusHistories = new HashSet<ApplicationStatusHistory>();
        }
    
        public int ApplicationID { get; set; }
        public int JobID { get; set; }
        public Nullable<int> CandidateUserID { get; set; }
        public string CandidateName { get; set; }
        public string CandidatePhone { get; set; }
        public string CandidateEmail { get; set; }
        public string CVFilePath { get; set; }
        public int StatusID { get; set; }
        public string HRNote { get; set; }
        public System.DateTime AppliedDate { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> UpdatedByUserID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual User User { get; set; }
        public virtual Job Job { get; set; }
        public virtual ApplicationStatus ApplicationStatus { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateFile> CandidateFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interview> Interviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationStatusHistory> ApplicationStatusHistories { get; set; }
    }
}
