//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATSMiniProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationStatusHistory
    {
        public int HistoryID { get; set; }
        public int ApplicationID { get; set; }
        public Nullable<int> OldStatusID { get; set; }
        public int NewStatusID { get; set; }
        public Nullable<int> ChangedByUserID { get; set; }
        public System.DateTime ChangedAt { get; set; }
        public string Note { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual ApplicationStatus ApplicationStatus { get; set; }
        public virtual ApplicationStatus ApplicationStatus1 { get; set; }
        public virtual User User { get; set; }
    }
}
