//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATSMiniProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int AuditLogID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ActionName { get; set; }
        public string TableName { get; set; }
        public Nullable<int> RecordID { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string IpAddress { get; set; }
    
        public virtual User User { get; set; }
    }
}
