//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATSMiniProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateFile
    {
        public int CandidateFileID { get; set; }
        public int ApplicationID { get; set; }
        public string OriginalFileName { get; set; }
        public string StoredFileName { get; set; }
        public string FilePath { get; set; }
        public string FileExtension { get; set; }
        public Nullable<int> FileSizeKB { get; set; }
        public System.DateTime UploadedAt { get; set; }
        public Nullable<int> UploadedByUserID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual User User { get; set; }
    }
}
