//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATSMiniProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview
    {
        public int InterviewID { get; set; }
        public int ApplicationID { get; set; }
        public System.DateTime InterviewDate { get; set; }
        public string InterviewLocation { get; set; }
        public Nullable<int> InterviewerUserID { get; set; }
        public string Note { get; set; }
        public string Result { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> UpdatedByUserID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
